name: nimbus_annotation
description: nimbus_annotation is a annotation for flutter_generator inspired by Chopper and Retrofit
repository: https://github.com/nimbus-org/nimbus4flutter/
version: 1.0.0+4

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.0.0