builders:
  nimbus_generator:
    import: "package:nimbus_generator/builder.dart"
    builder_factories: ["nimbusGenerator"]
    build_extensions: {".dart": [".nimbus_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]